FROM node:12.4.0-alpine
RUN apk add --update python python-dev py-pip build-base
RUN npm config set unsafe-perm true
RUN /bin/sh -c "apk add --no-cache bash nano"
RUN mkdir -p /logger/src
WORKDIR /logger
COPY package.json /logger
RUN npm install && npm install -g pm2 ts-node typescript
CMD npm run start-dev